import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'en' | 'ar'

const ar: Record<string, string> = {
  'Dashboard': 'لوحة التحكم',
  'Workspaces': 'مساحات العمل',
  'Workspace': 'مساحة العمل',
  'Workspace overview': 'نظرة عامة على مساحة العمل',
  'Projects': 'المشاريع',
  'Project': 'المشروع',
  'Tasks': 'المهام',
  'Members': 'الأعضاء',
  'Roles': 'الأدوار',
  'Roles & permissions': 'الأدوار والصلاحيات',
  'Settings': 'الإعدادات',
  'Collapse': 'طي القائمة',
  'Log out': 'تسجيل الخروج',
  'Use light theme': 'استخدام المظهر الفاتح',
  'Use dark theme': 'استخدام المظهر الداكن',
  'Open navigation': 'فتح القائمة',
  'Close navigation': 'إغلاق القائمة',
  'Current context': 'السياق الحالي',
  'Choose a project': 'اختر مشروعاً',
  'Choose or create a workspace before opening this section.': 'اختر مساحة عمل أو أنشئ واحدة قبل فتح هذا القسم.',
  'Choose a project before opening tasks.': 'اختر مشروعاً قبل فتح المهام.',
  'How to use Sanad': 'كيفية استخدام سند',
  'Quick guide': 'دليل سريع',
  'Close': 'إغلاق',
  'Create or choose a workspace.': 'أنشئ مساحة عمل أو اختر واحدة.',
  'Open Projects and create a project.': 'افتح المشاريع وأنشئ مشروعاً.',
  'Open the project and add tasks.': 'افتح المشروع وأضف المهام.',
  'Change task status directly from the list or board.': 'غيّر حالة المهمة مباشرة من القائمة أو اللوحة.',
  'Open workspaces': 'فتح مساحات العمل',
  'Good to see you': 'أهلاً بعودتك',
  'A live summary of the work you can access.': 'ملخص مباشر للعمل المتاح لك.',
  'New workspace': 'مساحة عمل جديدة',
  'Create workspace': 'إنشاء مساحة عمل',
  'Your dashboard is ready': 'لوحة التحكم جاهزة',
  'Create a workspace to begin tracking projects, tasks, and team progress.': 'أنشئ مساحة عمل لبدء متابعة المشاريع والمهام وتقدم الفريق.',
  'Project workload': 'حِمل المشاريع',
  'Task progress across accessible projects': 'تقدم المهام في المشاريع المتاحة',
  'No projects yet': 'لا توجد مشاريع بعد',
  'Open a workspace and create a project to see workload here.': 'افتح مساحة عمل وأنشئ مشروعاً لعرض حجم العمل هنا.',
  'Open tasks': 'مهام مفتوحة',
  'Completed': 'مكتملة',
  'All tasks': 'كل المهام',
  'In progress': 'قيد التنفيذ',
  'No project description has been added.': 'لم تتم إضافة وصف للمشروع.',
  'done': 'مكتمل',
  'Your organization': 'مؤسستك',
  'Separate teams, projects, and access rules into focused spaces.': 'نظّم الفرق والمشاريع وقواعد الوصول في مساحات واضحة.',
  'No workspaces yet': 'لا توجد مساحات عمل بعد',
  'Create your first workspace to start organizing projects and inviting collaborators.': 'أنشئ أول مساحة عمل لتنظيم المشاريع ودعوة المتعاونين.',
  'Team workspace': 'مساحة عمل للفريق',
  'Create a workspace': 'إنشاء مساحة عمل',
  'Workspaces keep people, projects, and roles together.': 'تجمع مساحة العمل الأشخاص والمشاريع والأدوار في مكان واحد.',
  'Workspace name': 'اسم مساحة العمل',
  'Cancel': 'إلغاء',
  'Creating…': 'جارٍ الإنشاء…',
  'A high-level view of this workspace and your access.': 'نظرة شاملة على مساحة العمل وصلاحياتك.',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Deleting…': 'جارٍ الحذف…',
  'Your role': 'دورك',
  'Rename workspace': 'إعادة تسمية مساحة العمل',
  'Save changes': 'حفظ التغييرات',
  'Updating…': 'جارٍ التحديث…',
  'Delete this workspace?': 'حذف مساحة العمل؟',
  'This permanently removes the workspace, its roles, and associated data. This action cannot be undone.': 'سيؤدي هذا إلى حذف مساحة العمل وأدوارها وبياناتها نهائياً. لا يمكن التراجع عن هذا الإجراء.',
  'Keep outcomes, ownership, and tasks organized by initiative.': 'نظّم النتائج والمسؤوليات والمهام حسب كل مبادرة.',
  'New project': 'مشروع جديد',
  'No projects in this workspace': 'لا توجد مشاريع في مساحة العمل',
  'Create a project to turn your team’s next objective into actionable work.': 'أنشئ مشروعاً لتحويل هدف فريقك القادم إلى عمل قابل للتنفيذ.',
  'Create project': 'إنشاء مشروع',
  'No description added.': 'لم تتم إضافة وصف.',
  'Open project': 'فتح المشروع',
  'Edit project': 'تعديل المشروع',
  'Create a project': 'إنشاء مشروع',
  'Give your team a clear place to track the work.': 'امنح فريقك مكاناً واضحاً لمتابعة العمل.',
  'Project name': 'اسم المشروع',
  'Description': 'الوصف',
  '(optional)': '(اختياري)',
  'Saving…': 'جارٍ الحفظ…',
  'Project updated.': 'تم تحديث المشروع.',
  'Project created.': 'تم إنشاء المشروع.',
  'Project deleted.': 'تم حذف المشروع.',
  'Track ownership, deadlines, status, and priority in one clear view.': 'تابع المسؤوليات والمواعيد والحالة والأولوية في عرض واضح.',
  'New task': 'مهمة جديدة',
  'Filters': 'التصفية',
  'List': 'قائمة',
  'Board': 'لوحة',
  'All statuses': 'كل الحالات',
  'All priorities': 'كل الأولويات',
  'Lowest': 'الأدنى',
  'Low': 'منخفضة',
  'Medium': 'متوسطة',
  'High': 'مرتفعة',
  'Urgent': 'عاجلة',
  'No due date': 'بلا موعد',
  'To Do': 'للعمل',
  'In Progress': 'قيد التنفيذ',
  'Done': 'مكتملة',
  'No tasks found': 'لا توجد مهام',
  'Create the first task for this project.': 'أنشئ أول مهمة لهذا المشروع.',
  'Try changing your filters, or create a task that matches them.': 'جرّب تغيير عوامل التصفية أو أنشئ مهمة مناسبة.',
  'Create task': 'إنشاء مهمة',
  'Task': 'المهمة',
  'Status': 'الحالة',
  'Priority': 'الأولوية',
  'Assigned to': 'مسندة إلى',
  'Due date': 'موعد الاستحقاق',
  'Actions': 'الإجراءات',
  'No description': 'لا يوجد وصف',
  'Unassigned': 'غير مسندة',
  'Overdue': 'متأخرة',
  'Previous': 'السابق',
  'Next': 'التالي',
  'No tasks here': 'لا توجد مهام هنا',
  'Edit task': 'تعديل المهمة',
  'Create a task': 'إنشاء مهمة',
  'Capture the outcome, owner, and timing clearly.': 'سجّل النتيجة والمسؤول والموعد بوضوح.',
  'Task title': 'عنوان المهمة',
  'Assignee': 'المسؤول',
  'Choose a role': 'اختر دوراً',
  'See who belongs to this workspace and keep responsibilities current.': 'اعرض أعضاء مساحة العمل وحدّث المسؤوليات.',
  'Add member': 'إضافة عضو',
  'No members found': 'لا يوجد أعضاء',
  'There are no visible members in this workspace.': 'لا يوجد أعضاء ظاهرون في مساحة العمل.',
  'Member': 'العضو',
  'Role': 'الدور',
  'Owner': 'المالك',
  'Manager': 'مدير',
  'Viewer': 'مشاهد',
  'Add a workspace member': 'إضافة عضو إلى مساحة العمل',
  'Invite someone using the email address on their Sanad account.': 'أضف شخصاً باستخدام البريد الإلكتروني لحسابه في سند.',
  'Email address': 'البريد الإلكتروني',
  'Adding…': 'جارٍ الإضافة…',
  'Control what each workspace role can view and change.': 'تحكّم فيما يمكن لكل دور عرضه وتغييره.',
  'New role': 'دور جديد',
  'No roles found': 'لا توجد أدوار',
  'This workspace has no visible roles.': 'لا توجد أدوار ظاهرة في مساحة العمل.',
  'Create role': 'إنشاء دور',
  'permissions': 'صلاحيات',
  'No permissions assigned': 'لا توجد صلاحيات مسندة',
  'Edit role': 'تعديل الدور',
  'Create a role': 'إنشاء دور',
  'Choose only the access this role needs.': 'اختر فقط الصلاحيات التي يحتاجها هذا الدور.',
  'Role name': 'اسم الدور',
  'Permissions': 'الصلاحيات',
  'Back to tasks': 'العودة إلى المهام',
  'Details': 'التفاصيل',
  'No description has been added for this task.': 'لم تتم إضافة وصف لهذه المهمة.',
  'Preferences': 'التفضيلات',
  'Manage your local display preference and session.': 'أدر تفضيلات العرض والجلسة على هذا الجهاز.',
  'Account': 'الحساب',
  'Name': 'الاسم',
  'Email': 'البريد الإلكتروني',
  'Appearance': 'المظهر',
  'Your choice is saved on this device.': 'يتم حفظ اختيارك على هذا الجهاز.',
  'Light': 'فاتح',
  'Dark': 'داكن',
  'Language': 'اللغة',
  'English': 'الإنجليزية',
  'Arabic': 'العربية',
  'Welcome back': 'أهلاً بعودتك',
  'Turn ambitious plans into steady progress.': 'حوّل الخطط الطموحة إلى تقدم ثابت.',
  'Clear project visibility': 'رؤية واضحة للمشاريع',
  'Flexible team permissions': 'صلاحيات مرنة للفريق',
  'Focused task workflows': 'مسارات عمل مركّزة',
  'No noisy busywork': 'عمل منظم بلا تشتيت',
  'Built around teamwork, clarity, and steady support.': 'مصمم للتعاون والوضوح والدعم المستمر.',
  'Create your account': 'إنشاء حسابك',
  'Sign in to continue to your workspace.': 'سجّل الدخول للمتابعة إلى مساحة عملك.',
  'Start organizing your team’s work today.': 'ابدأ بتنظيم عمل فريقك اليوم.',
  'Password': 'كلمة المرور',
  'Show password': 'إظهار كلمة المرور',
  'Hide password': 'إخفاء كلمة المرور',
  'Sign in': 'تسجيل الدخول',
  'Signing in…': 'جارٍ تسجيل الدخول…',
  'New to Sanad?': 'جديد في سند؟',
  'Create an account': 'إنشاء حساب',
  'Already have an account?': 'لديك حساب بالفعل؟',
  'Creating account…': 'جارٍ إنشاء الحساب…',
  'We couldn’t load this page': 'تعذر تحميل هذه الصفحة',
  'Try again': 'إعادة المحاولة',
  'Loading…': 'جارٍ التحميل…',
  'Restoring your session…': 'جارٍ استعادة جلستك…',
  'This page is off the map': 'هذه الصفحة غير موجودة',
  'The page may have moved, or the address may be incorrect.': 'ربما تم نقل الصفحة أو أن العنوان غير صحيح.',
  'Back to dashboard': 'العودة إلى لوحة التحكم',
}

type LanguageContextValue = {
  language: Language
  setLanguage: (language: Language) => void
  t: (text: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem('language') === 'ar' ? 'ar' : 'en')
  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
  }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: (text: string) => language === 'ar' ? ar[text] ?? text : text }), [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const value = useContext(LanguageContext)
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider')
  return value
}
